### ISSUE TITLE
Split position on start

### ISSUE THREAD

**Issue by pju-** [ZombieHippie/Touch-Splitter-jQuery#8]
Hello, great work on this splitter, really easy and performative!

Is there an easy way to set up this splitter so that the bar doesn't start in the middle, but (e.g.) at 66% width or height?

Thanks!

**Comment by ZombieHippie** [comment]
Hello,

Yes, you should be able to do something like this:
```javascript
$('#main-splitter').touchSplitter(options)
var touchsplitter =

**Comment by ZombieHippie** [comment]
Sorry, I accidentally hit Close and comment when replying.

```javascript
$('#main-splitter').touchSplitter(options)
$('#main-splitter')[0].touchSplitter.barPosition = .66 // 66%
$('#main-splitter')[0].touchSplitter.setPercentages()
```

let me test this first though ;-)

**Comment by pju-** [comment]
Wow man, thanks for the quick reply. 
Actually, I just now did my own rewrite with an added option "startPosition". Seems to work just fine. Do you want me to send you a PR?

**Comment by ZombieHippie** [comment]
Yes, so if you do:
```javascript
var splitter = $('#main-splitter').touchSplitter(options)
splitter.barPosition = .66 // 66%
splitter.setPercentages() // recalculates positions and percentages
```

You should be in the clear ;-)

**Comment by ZombieHippie** [comment]
@pju- yeah if you added an option to the coffee source and rerun the cakefile, I'll check it out and merge it :+1:

**Comment by pju-** [comment]
Perfect, I've sent you the PR now.
